#+TODO: TODO(t) DOING(i) WAITING(w) POSTPONED(p) | CANCELLED(c) DONE(d)

* DONE .gitignore file
CLOSED: [2020-08-01 Sat 15:20]

* DONE COPYING file
CLOSED: [2020-08-01 Sat 15:20]

* DONE initial syntax table
CLOSED: [2020-08-01 Sat 16:23]

* DONE indent function
  CLOSED: [2020-08-12 on. 22:46]
using SMIE, we get a lot of indentation help from the
get-go.  However, it is pretty hard to configure.  This commit is only a first
attempt, offering an initial jump-off point.  It indents most of the examples
found at [[https://harelang.org/style/][Style guide]], but not all yet.

Also, useful article [[https://programming-journal.org/2021/5/1/][here]].

We now offer some easy to use indentation helper commands, simplifying the
indentation when it fails miserably.

* DONE index function for imenu

* CANCELLED avoid using symbol at point as default value on imenu
CLOSED: [2020-08-03 Mon 15:31]
Seems like when you're on a symbol, imenu uses it as default value. But
when you're in whitespace, it never shows that prompt with the default
value. I've not found a way of avoiding using a default value, but seems
to me that can be useful from time to time.

* DONE comments regexp
CLOSED: [2020-08-01 Sat 17:19]

* DONE @like builtins doesn't use face properly
CLOSED: [2020-08-01 Sat 16:23]

* DONE beginning/end-of-defun-functions
  CLOSED: [2020-08-10 ma. 20:14]
* DONE use =font-lock-type-face= for types
